/**
 * Registry of every real tenant/admin/partner page mirrored under
 * `(preview)/preview/**` (docs/DESIGN_SYSTEM.md §UI Preview Mode). Backs
 * `/preview` (the route index) — generated once from the actual mirror
 * files; a dynamic segment's example href (`[id]` etc.) points at
 * `"demo"`, which every fixture-backed data query in
 * `apps/web/src/lib/preview/mock-fetch.ts` happily accepts (filters are
 * not honored — every request just returns the fixture rows).
 *
 * Regenerate by re-running the DS cluster's mirror generator whenever a
 * real page/layout is added, removed, or moved.
 */
export interface PreviewRoute {
  /** The canonical (possibly-dynamic) URL pattern, e.g. `/preview/dashboard/calls/[id]`. */
  url: string;
  /** A concrete, clickable href for this pattern. */
  href: string;
  area: "Tenant dashboard" | "Admin cockpit" | "Partner portal";
  label: string;
  /** Repo-relative path of the real page this mirrors. */
  source: string;
}

export const PREVIEW_ROUTES: PreviewRoute[] = [
  {
    url: "/preview/cockpit/alerts",
    href: "/preview/cockpit/alerts",
    area: "Admin cockpit",
    label: "Alerts",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/alerts/page.tsx",
  },
  {
    url: "/preview/cockpit/config-lab",
    href: "/preview/cockpit/config-lab",
    area: "Admin cockpit",
    label: "Config Lab",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/config-lab/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/bottlenecks",
    href: "/preview/cockpit/margin/bottlenecks",
    area: "Admin cockpit",
    label: "Bottlenecks",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/bottlenecks/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/cac",
    href: "/preview/cockpit/margin/cac",
    area: "Admin cockpit",
    label: "Cac",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/cac/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/calls",
    href: "/preview/cockpit/margin/calls",
    area: "Admin cockpit",
    label: "Calls",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/calls/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/customers",
    href: "/preview/cockpit/margin/customers",
    area: "Admin cockpit",
    label: "Customers",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/customers/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/customers/[tenantId]",
    href: "/preview/cockpit/margin/customers/demo",
    area: "Admin cockpit",
    label: "Customers detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/customers/[tenantId]/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/drift",
    href: "/preview/cockpit/margin/drift",
    area: "Admin cockpit",
    label: "Drift",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/drift/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/referrals",
    href: "/preview/cockpit/margin/referrals",
    area: "Admin cockpit",
    label: "Referrals",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/referrals/page.tsx",
  },
  {
    url: "/preview/cockpit/margin/waterfall",
    href: "/preview/cockpit/margin/waterfall",
    area: "Admin cockpit",
    label: "Waterfall",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/margin/waterfall/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach",
    href: "/preview/cockpit/outreach",
    area: "Admin cockpit",
    label: "Outreach",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach/campaigns",
    href: "/preview/cockpit/outreach/campaigns",
    area: "Admin cockpit",
    label: "Campaigns",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/campaigns/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach/campaigns/[id]",
    href: "/preview/cockpit/outreach/campaigns/demo",
    area: "Admin cockpit",
    label: "Campaigns detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/campaigns/[id]/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach/campaigns/new",
    href: "/preview/cockpit/outreach/campaigns/new",
    area: "Admin cockpit",
    label: "New",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/campaigns/new/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach/leads",
    href: "/preview/cockpit/outreach/leads",
    area: "Admin cockpit",
    label: "Leads",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/leads/page.tsx",
  },
  {
    url: "/preview/cockpit/outreach/replies",
    href: "/preview/cockpit/outreach/replies",
    area: "Admin cockpit",
    label: "Replies",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/outreach/replies/page.tsx",
  },
  {
    url: "/preview/cockpit/partners",
    href: "/preview/cockpit/partners",
    area: "Admin cockpit",
    label: "Partners",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/partners/page.tsx",
  },
  {
    url: "/preview/cockpit/partners/[id]",
    href: "/preview/cockpit/partners/demo",
    area: "Admin cockpit",
    label: "Partners detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/partners/[id]/page.tsx",
  },
  {
    url: "/preview/cockpit/settings",
    href: "/preview/cockpit/settings",
    area: "Admin cockpit",
    label: "Settings",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/settings/page.tsx",
  },
  {
    url: "/preview/cockpit/support",
    href: "/preview/cockpit/support",
    area: "Admin cockpit",
    label: "Support",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/support/page.tsx",
  },
  {
    url: "/preview/cockpit/support/[id]",
    href: "/preview/cockpit/support/demo",
    area: "Admin cockpit",
    label: "Support detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/support/[id]/page.tsx",
  },
  {
    url: "/preview/cockpit/templates",
    href: "/preview/cockpit/templates",
    area: "Admin cockpit",
    label: "Templates",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/templates/page.tsx",
  },
  {
    url: "/preview/cockpit/templates/[vertical]",
    href: "/preview/cockpit/templates/demo",
    area: "Admin cockpit",
    label: "Templates detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/templates/[vertical]/page.tsx",
  },
  {
    url: "/preview/cockpit/tenants",
    href: "/preview/cockpit/tenants",
    area: "Admin cockpit",
    label: "Tenants",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/tenants/page.tsx",
  },
  {
    url: "/preview/cockpit/tenants/[id]",
    href: "/preview/cockpit/tenants/demo",
    area: "Admin cockpit",
    label: "Tenants detail",
    source: "apps/web/src/app/[locale]/(admin)/cockpit/tenants/[id]/page.tsx",
  },
  {
    url: "/preview/portal",
    href: "/preview/portal",
    area: "Partner portal",
    label: "Portal",
    source: "apps/web/src/app/[locale]/(partner)/portal/page.tsx",
  },
  {
    url: "/preview/portal/customers",
    href: "/preview/portal/customers",
    area: "Partner portal",
    label: "Customers",
    source: "apps/web/src/app/[locale]/(partner)/portal/customers/page.tsx",
  },
  {
    url: "/preview/portal/disclosure",
    href: "/preview/portal/disclosure",
    area: "Partner portal",
    label: "Disclosure",
    source: "apps/web/src/app/[locale]/(partner)/portal/disclosure/page.tsx",
  },
  {
    url: "/preview/portal/payouts",
    href: "/preview/portal/payouts",
    area: "Partner portal",
    label: "Payouts",
    source: "apps/web/src/app/[locale]/(partner)/portal/payouts/page.tsx",
  },
  {
    url: "/preview/portal/settings",
    href: "/preview/portal/settings",
    area: "Partner portal",
    label: "Settings",
    source: "apps/web/src/app/[locale]/(partner)/portal/settings/page.tsx",
  },
  {
    url: "/preview/portal/w9",
    href: "/preview/portal/w9",
    area: "Partner portal",
    label: "W9",
    source: "apps/web/src/app/[locale]/(partner)/portal/w9/page.tsx",
  },
  {
    url: "/preview/dashboard",
    href: "/preview/dashboard",
    area: "Tenant dashboard",
    label: "Dashboard",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/page.tsx",
  },
  {
    url: "/preview/dashboard/agent",
    href: "/preview/dashboard/agent",
    area: "Tenant dashboard",
    label: "Agent",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/faq",
    href: "/preview/dashboard/agent/faq",
    area: "Tenant dashboard",
    label: "Faq",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/faq/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/greeting",
    href: "/preview/dashboard/agent/greeting",
    area: "Tenant dashboard",
    label: "Greeting",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/greeting/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/hours",
    href: "/preview/dashboard/agent/hours",
    area: "Tenant dashboard",
    label: "Hours",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/hours/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/instructions",
    href: "/preview/dashboard/agent/instructions",
    area: "Tenant dashboard",
    label: "Instructions",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/instructions/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/language",
    href: "/preview/dashboard/agent/language",
    area: "Tenant dashboard",
    label: "Language",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/language/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/manual-mode",
    href: "/preview/dashboard/agent/manual-mode",
    area: "Tenant dashboard",
    label: "Manual Mode",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/manual-mode/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/services",
    href: "/preview/dashboard/agent/services",
    area: "Tenant dashboard",
    label: "Services",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/services/page.tsx",
  },
  {
    url: "/preview/dashboard/agent/vertical-details",
    href: "/preview/dashboard/agent/vertical-details",
    area: "Tenant dashboard",
    label: "Vertical Details",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/agent/vertical-details/page.tsx",
  },
  {
    url: "/preview/dashboard/billing",
    href: "/preview/dashboard/billing",
    area: "Tenant dashboard",
    label: "Billing",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/billing/page.tsx",
  },
  {
    url: "/preview/dashboard/bookings",
    href: "/preview/dashboard/bookings",
    area: "Tenant dashboard",
    label: "Bookings",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/bookings/page.tsx",
  },
  {
    url: "/preview/dashboard/calls",
    href: "/preview/dashboard/calls",
    area: "Tenant dashboard",
    label: "Calls",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/calls/page.tsx",
  },
  {
    url: "/preview/dashboard/calls/[id]",
    href: "/preview/dashboard/calls/demo",
    area: "Tenant dashboard",
    label: "Calls detail",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/calls/[id]/page.tsx",
  },
  {
    url: "/preview/dashboard/customers",
    href: "/preview/dashboard/customers",
    area: "Tenant dashboard",
    label: "Customers",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/customers/page.tsx",
  },
  {
    url: "/preview/dashboard/customers/[id]",
    href: "/preview/dashboard/customers/demo",
    area: "Tenant dashboard",
    label: "Customers detail",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/customers/[id]/page.tsx",
  },
  {
    url: "/preview/dashboard/delivery",
    href: "/preview/dashboard/delivery",
    area: "Tenant dashboard",
    label: "Delivery",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/delivery/page.tsx",
  },
  {
    url: "/preview/dashboard/integrations",
    href: "/preview/dashboard/integrations",
    area: "Tenant dashboard",
    label: "Integrations",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/integrations/page.tsx",
  },
  {
    url: "/preview/dashboard/messages",
    href: "/preview/dashboard/messages",
    area: "Tenant dashboard",
    label: "Messages",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/messages/page.tsx",
  },
  {
    url: "/preview/dashboard/messages/[phone]",
    href: "/preview/dashboard/messages/demo",
    area: "Tenant dashboard",
    label: "Messages detail",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/messages/[phone]/page.tsx",
  },
  {
    url: "/preview/dashboard/orders",
    href: "/preview/dashboard/orders",
    area: "Tenant dashboard",
    label: "Orders",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/orders/page.tsx",
  },
  {
    url: "/preview/dashboard/orders/[id]",
    href: "/preview/dashboard/orders/demo",
    area: "Tenant dashboard",
    label: "Orders detail",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/orders/[id]/page.tsx",
  },
  {
    url: "/preview/dashboard/phone-setup",
    href: "/preview/dashboard/phone-setup",
    area: "Tenant dashboard",
    label: "Phone Setup",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/phone-setup/page.tsx",
  },
  {
    url: "/preview/dashboard/refer",
    href: "/preview/dashboard/refer",
    area: "Tenant dashboard",
    label: "Refer",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/refer/page.tsx",
  },
  {
    url: "/preview/dashboard/setup",
    href: "/preview/dashboard/setup",
    area: "Tenant dashboard",
    label: "Setup",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/setup/page.tsx",
  },
  {
    url: "/preview/dashboard/setup/offerings",
    href: "/preview/dashboard/setup/offerings",
    area: "Tenant dashboard",
    label: "Offerings",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/setup/offerings/page.tsx",
  },
  {
    url: "/preview/dashboard/setup/offerings/import",
    href: "/preview/dashboard/setup/offerings/import",
    area: "Tenant dashboard",
    label: "Import",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/setup/offerings/import/page.tsx",
  },
  {
    url: "/preview/dashboard/setup/resources",
    href: "/preview/dashboard/setup/resources",
    area: "Tenant dashboard",
    label: "Resources",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/setup/resources/page.tsx",
  },
  {
    url: "/preview/dashboard/support",
    href: "/preview/dashboard/support",
    area: "Tenant dashboard",
    label: "Support",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/support/page.tsx",
  },
  {
    url: "/preview/dashboard/support/[id]",
    href: "/preview/dashboard/support/demo",
    area: "Tenant dashboard",
    label: "Support detail",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/support/[id]/page.tsx",
  },
  {
    url: "/preview/dashboard/team",
    href: "/preview/dashboard/team",
    area: "Tenant dashboard",
    label: "Team",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/team/page.tsx",
  },
  {
    url: "/preview/dashboard/test-agent",
    href: "/preview/dashboard/test-agent",
    area: "Tenant dashboard",
    label: "Test Agent",
    source: "apps/web/src/app/[locale]/(tenant)/dashboard/test-agent/page.tsx",
  },
];
